meta:
  name: pepepad-v
  version: 0.0.1
  engine: 4.1.0
  author: pedroren
units:
  kx: u
  ky: u
  p: 0
  # padding for outer keys
  px: 2
  kpx: kx+px
  py: 2
  kpy: ky+py
  # components size
  mcu_y: 34.1
  mcu_x: 18.3
  mcu_d: 3.3+12 # mcu+sockets
  enc_x: 11.7
  enc_y: 12
  enc_d: 11.5
  batt_x: 18
  batt_y: 32
  batt_d: 6.5 
  # Defaults to M2 Screws
  screw_size: 1.5
  standoff_size: 2.5
  # Case
  case_d: 1.5
  pcb_d: 1.6
  plate_pcb_gap: 3
  bottom_pcb_gap: 3
  usb_access_x: 13
  usb_access_d: 6
  case_y: case_d+bottom_pcb_gap+pcb_d+plate_pcb_gap+pcb_d
points:
  zones:
    matrix:
      anchor:
        shift: [100, -120] #kicad
      key:
        padding: ky+p
        spread: kx+p
        tags: mx_key
      columns:
        left-outer:
          key.column_net: P008
        left-inner:
          key.column_net: P022
        right-inner:
          key.column_net: P024
        right-outer:
          key.column_net: P100
      rows:
        bottom:
          row_net: P104
        middle:
          row_net: P106
        top:
          row_net: P031
    arrow_cluster:
      key:
        padding: ky+p
        spread: kx+p
        tags: mx_key
      anchor:
        ref: matrix_left-outer_bottom
        shift: [.5kx, -2.5ky]
      columns:
        left:
          key.column_net: P008
          rows.top.skip: true
        middle:
          key.column_net: P022
        right:
          rows.top.skip: true
          key.column_net: P024
      rows:
        bottom:        
          row_net: P029    
        top:
          row_net: P002
    encoders:
      key.tags: [encoder]
      anchor:
        ref: matrix_left-outer_bottom
        shift: [0, -1.25ky]
      columns:
        left:
          key:
            pin_a: P115
            pin_c: P113
            column_net: P008
        right:
          key:
            shift: [2kx, 0]
            pin_a: P111
            pin_c: P009
            column_net: P100
      rows:
        enc-row:
          row_net: P029
    mount1:
      key.tags: [mount]
      anchor:
        ref.aggregate.parts: [
          matrix_left-outer_top,  
          matrix_left-inner_top ,
          matrix_left-inner_middle,
          matrix_left-outer_middle]
    mount2:
      key.tags: [mount]
      anchor:
        ref.aggregate.parts: [
          matrix_right-outer_top,  
          matrix_right-inner_top ,
          matrix_right-inner_middle,
          matrix_right-outer_middle]
        shift: [0,0]
    mount3:
      key.tags: [mount]
      anchor:
        ref: encoders_left_enc-row
        shift: [.5kx, -.5ky]
    mount4:
      key.tags: [mount]
      anchor:
        ref: encoders_right_enc-row
        shift: [-.5kx, -.5ky]        
    controller:
      key.tags: [mcu]
      anchor:        
        ref.aggregate.parts: [          
          matrix_right-inner_top ,
          matrix_left-inner_top]
        shift: [-9,1ky+2]
    reset_button:
      key.tags: [reset_btn]          
      anchor: 
        - ref: controller
          shift: [.75mcu_y+8, 5]
    power_button:
      key.tags: [power_btn]          
      anchor: 
        - ref: controller
          shift: [.75mcu_y+8, -5]                  
outlines:
  keys_socket:
    - what: rectangle
      where: [mx_key]
      size: [14, 14]
  keycaps:
    - what: rectangle 
      where: [mx_key]
      size: [kx, ky] 
      corner: 1
  switches:
    - what: rectangle
      where: [mx_key]
      size: 14
  keywell:
    - what: rectangle 
      where: [mx_key, encoder]
      size: [kpx, kpy] 
      corner: 2
      fillet: 4
      bound: true 
  controller:
    - what: rectangle
      where: [mcu]
      size: [mcu_x, mcu_y]           
  controller_area:
    - what: rectangle
      where: [mcu]        
      size: [1.5mcu_x-5, 1.5mcu_y+2]
      corner: px      
      adjust:
        shift: [10, 0]      
        rotate: 90
  encoders:
    - what: rectangle
      where: [encoder]
      size: [enc_x+.5, enc_y+.5]                   
  arrows_patch:
    - what: polygon    
      operation: stack
      fillet: 2
      points:
          - ref: matrix_left-outer_bottom
            shift: [-.5kx, 0]      
          - ref: encoders_left_enc-row
            shift: [-.5kx, 0]        
          - ref: arrow_cluster_left_bottom
            shift: [-.5kx, 0]          
          - ref: arrow_cluster_right_bottom
            shift: [.5kx, 0]            
          - ref: encoders_right_enc-row
            shift: [.5kx, 0]      
          - ref: matrix_right-outer_bottom
            shift: [.5kx, 0]                    
  screw_holes:
    - what: circle
      radius: screw_size    
      where: [mount]
  mounting_holes:
    - what: circle
      radius: standoff_size    
      where: [mount]
  pcb_support:
    - what: outline
      name: mounting_holes
      expand: 1
  base_outline:
    - keywell
    - name: arrows_patch
      operation: add
      joints: beveled
      fillet: 4
      bound: true
    - controller_area      
    - -screw_holes
  outer_outline:  
    - what: outline
      name: base_outline
      expand: case_d+1
      joints: beveled
      fillet: 2
  pcb:
    - base_outline
    - -mounting_holes  
  switch_plate:
    - base_outline   
    - -encoders
    - -switches
  preview:    
    - base_outline
    - -keycaps
pcbs:    
  pekepadv:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      gnd_fillzone:
        what: ceoloide/utility_filled_zone
        where:
          ref.aggregate.parts: [matrix_left-outer_top]
      mx_hotswap:
        what: ceoloide/switch_mx
        where: [mx_key]
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: [mx_key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/D_SOD-123.step'
        adjust:
          shift: [0, -5]
          rotate: 180
      diode_enc:
        what: ceoloide/diode_tht_sod123
        where: [encoder]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/D_SOD-123.step'
          diode_3dmodel_xyz_rotation: [0,0,0]
        adjust:
          shift: [0, 4]
          rotate: 180
      mcu:
        what: ceoloide/mcu_nice_nano
        where: [mcu]
          #ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        adjust: 
          #shift: [0, -.25k]
          rotate: 90
        params:
          reversible: false
          P21: P031
          P20: P029
          P19: P002
          P18: P115
          P15: P113
          P14: P111
          P16: P010
          P10: P009
          P1: P006
          P0: P008
          P2: P017
          P3: P020
          P4: P022
          P5: P024
          P6: P100
          P7: P011
          P8: P104
          P9: P106
      encoders:
        what: ceoloide/rotary_encoder_ec11_ec12
        where: [encoder]
        params:
          A: "{{pin_a}}"
          C: "{{pin_c}}"
          S1: "{{colrow}}"
          S2: "{{column_net}}"
          mirror.S1: "{{column_net}}"
          mirror.S2: "{{colrow}}"
          include_plate_hole_marking: true
          include_plated_mounting_holes: false
        adjust:
          rotate: 0
      reset_button:
        what: ceoloide/reset_switch_smd_side
        params:
          side: B 
          reset_switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/Panasonic_EVQPUJ_EVQPUA.step'
          reset_switch_3dmodel_xyz_rotation: [0,0,-180]
        where: reset_btn
        adjust:
          shift: [0,0]
          rotate: -90
      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          side: B
          switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/SW_SPDT_PCM12.step'
          switch_3dmodel_xyz_rotation: [0,0,-90]
        where: power_btn
        adjust:
          shift: [0,0]
          rotate: 0
      batt_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: B
          battery_connector_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal.step'
          battery_connector_3dmodel_xyz_rotation: [0,0,180]
          battery_connector_3dmodel_xyz_offset: [1, 0, 0]
        where: power_btn
        adjust:        
          shift: [-7, -4]
          rotate: -180
      mounting_holes:
          what: ceoloide/mounting_hole_npth
          where: [mount]
      oled:
        what: ceoloide/display_nice_view
        params:
          reversible: false
          side: "F"
          MOSI: P011
          SCK: P010
          CS: P006
        where:
          ref.aggregate.parts: [controller]
          shift: [3,0]
          rotate: 90
cases:
  _standoffs:
    - name: mounting_holes
      extrude: case_y-pcb_d
  _pcb_support:
    - name: pcb_support
      extrude: pcb_d+bottom_pcb_gap
  _holes:
    - name: screw_holes
      extrude: case_y      
  _wall:
    - name: outer_outline
      extrude: case_y
    - name: base_outline
      extrude: case_y
      operation: subtract
    - -_holes      
  bottom_plate:
    - name: base_outline
      extrude: case_d
  switch_plate:    
    - name: switch_plate
      extrude: pcb_d
  sandwich_case:    
    - bottom_plate      
    - _standoffs
    - _pcb_support
    - -_holes
  case:
    - _wall
    - sandwich_case