meta:
  name: pepekey
  version: 0.0.0
  engine: 4.1.0
  author: pedroren
units:
  k: u
  p: 1
  px: 4
  py: 2
  kpx: k+px
  kpy: k+py
  # components size
  mcu_y: 34.1
  mcu_x: 18.3
  mcu_d: 3.3+12 # mcu+sockets
  batt_x: 18
  batt_y: 32
  batt_d: 6.5 
  # Defaults to M2 Screws
  screw_size: 1.5
  standoff_size: 2.5
  # Case
  case_d: 2
  pcb_d: 1.6
  plate_pcb_gap: 5
  bottom_pcb_gap: 4
  usb_access_x: 13
  usb_access_d: 7
  case_y: case_d+bottom_pcb_gap+pcb_d+plate_pcb_gap+pcb_d
points:
  zones:
    matrix:
      anchor:
        shift: [100, -120] #kicad
      key:
        padding: p+u
        spread: p+u
        tags: mx_key
      columns:
        outer:
          key:
            column_net: P008
        pinky:
          key:
            column_net: P022
        ring:
          key:
            stagger: 3u/4
            column_net: P024
        middle:
          key:
            stagger: 1u/4
            column_net: P100
        index:
          key:
            stagger: -1u/4
            column_net: P011
        inner:
          key:
            stagger: -1u/8
            column_net: P106
      rows:
        bottom:
          row_net: P031
        home:
          row_net: P025
        top:
          row_net: P002
        num:
          row_net: P115
    thumbs:
      key:
        padding: 1u
        spread: u+1u/8
        tags: mx_key
      anchor:
        ref:  matrix_inner_bottom
        shift:  [-1u/2,  -1u]
      columns:
        outer:
          key:
            splay: -10
            origin: [-0.7 u, +0.5 u]
            column_net: P100
        middle:
          key:
            splay: -10
            #stagger: -1u/6
            origin: [-0.5 u, -0.5 u]
            #rotate: -6
            column_net: P011
        inner:
          key:
            splay: -10
            #stagger: -1u/4
            #rotate: -6
            origin: [-0.5 u, -0.5 u]
            column_net: P106
      rows:
        thumbrow:
          row_net: P113
    mount_top_left:
      key.tags: [mount]
      anchor:
        - ref: matrix_ring_top
          shift: [-0.5 k, 0.5 k]
    mount_bottom_left:
      key.tags: [mount]
      anchor:
        - ref: matrix_pinky_bottom
          shift: [0.6 k, 0.1 k]
    mount_top_right:
      key.tags: [mount]
      anchor:
        - ref: matrix_inner_top
          shift: [-0.52 k, .5k+1]
    mount_palm:
      key.tags: [mount]
      anchor:
        - ref: matrix_index_bottom
          shift: [-0.25 k, -.7 k]
    mount_thumb:
      key.tags: [mount]
      anchor:
        - ref: thumbs_inner_thumbrow
          shift: [-0.6 k, 0]
    controller:
      key.tags: [mcu]          
      anchor: 
        - ref: matrix_inner_top
          shift: [.5k+mcu_x-2, .5k]
          rotate: 0
    reset_button:
      key.tags: [reset_btn]          
      anchor: 
        - ref: controller
          shift: [.5mcu_x+3, 0]
    power_button:
      key.tags: [power_btn]          
      anchor: 
        - ref: controller
          shift: [.5mcu_x+3, -.75mcu_y+3]          
outlines:
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kpx, kpy]
      corner: px
  keycaps:
    - what: rectangle 
      where: [mx_key]
      asym: source
      size: [k, k] 
      corner: 1
  switches:
    - what: rectangle
      where: [mx_key]
      asym: source
      size: 14
  controller:
    - what: rectangle
      where: [mcu]
      asym: source
      size: [mcu_x, mcu_y]
  usb_access:      
    - what: rectangle
      where: [mcu]
      asym: source
      size: [usb_access_x, usb_access_d]
      adjust.shift: [0, .5mcu_y+3]
      corner: 2
  reset_access:
    - what: circle
      where: reset_button
      radius: 2
      adjust.shift: [1.5, 0]
  power_access:      
    - what: rectangle
      where: power_button
      size: [case_d+2, usb_access_x]
      adjust.shift: [case_d+2, 0]    
  controller_area:
    - what: rectangle
      where: [mcu]        
      size: [1.5mcu_x+2, 1.5mcu_y]
      corner: px
      adjust.shift: [0,-.25mcu_y]
  battery_area:
    - what: rectangle
      where: [mcu]
      size: [1.5mcu_x+2, batt_y+9]
      adjust.shift: [0,-.5mcu_y-.5batt_y-3]
      corner: px
  screw_holes:
    - what: circle
      radius: screw_size    
      where: [mount]
  mounting_holes:
    - what: circle
      radius: standoff_size    
      where: [mount]
  pcb_support:
    - what: outline
      name: mounting_holes
      expand: 1
  keyarea: #starting bottom left
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref:  matrix_outer_bottom
          shift: [-0.5kpx, -0.6kpy]
        - ref:  matrix_pinky_bottom
          shift: [0kpx, -0.6kpy]
        - ref:  matrix_pinky_bottom
          shift: [0.5kpx, -0.6kpy]
        - ref:  matrix_ring_bottom
          shift: [0kpx, -0.7kpy]
        - ref:  matrix_index_bottom
          shift: [-0.5kpx, -0.7kpy]
        - ref:  thumbs_outer_thumbrow
          shift: [-0.5kpx, -0.6kpy]
        - ref:  thumbs_outer_thumbrow
          shift: [0kpx, -0.6kpy]
        - ref:  thumbs_middle_thumbrow
          shift: [0kpx, -0.65kpy]
        - ref:  thumbs_inner_thumbrow
          shift: [0.6kpx, -0.7kpy]
        - ref:  thumbs_inner_thumbrow
          shift: [0.6kpx, 0.7kpy]
        - ref:  thumbs_middle_thumbrow
          shift: [0kpx, 0.75kpy]
        - ref:  matrix_inner_bottom
          shift: [0.6kpx, 0kpy]
        - ref:  matrix_inner_num
          shift: [0.6kpx, 0.5kpy]
        - ref:  matrix_middle_num
          shift: [0.6kpx, 0.6kpy]
        - ref:  matrix_middle_num
          shift: [-0.5kpx, 0.6kpy]
        - ref:  matrix_ring_num
          shift: [-0.5kpx, 0.5kpy]
        - ref:  matrix_pinky_num
          shift: [0.25kpx, 0.6kpy]
        - ref:  matrix_pinky_num
          shift: [-0.5kpx, 0.6kpy]
        - ref:  matrix_outer_num
          shift: [-0.5kpx, 0.6kpy]
  keywell:
    - "keyarea"
  base_outline:
    - keywell
    - controller_area
  bottom_outline:
    - base_outline
    - -screw_holes
    - battery_area
  outer_area:
    - what: outline
      name: bottom_outline
      expand: case_d+.5
      joints: beveled
  plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"     
  pcb:
    - "base_outline"
    - "-mounting_holes"         
  combo:
    - keyarea
    - -keycaps
    - controller_area
    - screw_holes
  switches_screws: #For verification
    - base_outline
    - -switches
    - -mounting_holes
pcbs:
  top_plate:
    template: kicad8
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
  bottom_plate:
    template: kicad8
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts        
  pepekey:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      gnd_fillzone:
        what: ceoloide/utility_filled_zone
        where:
          ref.aggregate.parts: [matrix_outer_top]
      mounting_holes:
        what: ceoloide/mounting_hole_npth
        where: [mount]   
      mx_hotswap:
        what: ceoloide/switch_mx
        where:
          - /matrix_.*/
          - /thumbs_.*/
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where:
          - /matrix_.*/
          - /thumbs_.*/
        adjust.shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/D_SOD-123.step'
      mcu:
        what: ceoloide/mcu_nice_nano
        where: mcu
        params:
          #side: F
          reversible: false
          P21: P031
          P20: P029
          P19: P002
          P18: P115
          P15: P113
          P14: P111
          P16: P010
          P10: P009
          P1: P006
          P0: P008
          P2: P017
          P3: P020
          P4: P022
          P5: P024
          P6: P100
          P7: P011
          P8: P104
          P9: P106
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where:
          ref:
            - reset_button
          shift: [0, 0]
          rotate: 270
        params:
          from: GND
          to: RST
          reset_switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/Panasonic_EVQPUJ_EVQPUA.step'
          reset_switch_3dmodel_xyz_rotation: [0,0,0]
      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          side: F
          switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/SW_SPDT_PCM12.step'
          switch_3dmodel_xyz_rotation: [0,0,-90]
        where:
          ref:
            - power_button
          shift: [0, 0]
          rotate: 0
      batt_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: F
          battery_connector_3dmodel_filename: '${KIPRJMOD}/../../../kicad/3dmodels/JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal.step'
          battery_connector_3dmodel_xyz_rotation: [0,0,0]
          battery_connector_3dmodel_xyz_offset: [-1, 0, 0]
        where:
          ref:
            - controller
          shift: [.5k-3, -.5mcu_y-5]
          rotate: -90
cases:
  _pcb:
    - name: pcb
      extrude: pcb_d
      shift: [0,0,+pcb_d+bottom_pcb_gap]
  _switch_plate:
      - name: plate
        extrude: pcb_d
        shift: [0, 0, case_y-pcb_d]
  _standoffs:
    - name: mounting_holes
      extrude: case_y-pcb_d
  _pcb_support:
    - name: pcb_support
      extrude: pcb_d+bottom_pcb_gap
  _holes:
    - name: screw_holes
      extrude: case_y
  _usb_cutout:
    - name: usb_access
      extrude: case_d+2
      shift: [0, 0, case_d+pcb_d+bottom_pcb_gap]
      rotate: [90,0,0]
  _reset_cutout:
    - name: reset_access
      extrude: case_d+2
      shift: [0, 0, case_d+.5pcb_d+bottom_pcb_gap]
      rotate: [0,90,0]
  _power_cutout:
    - name: power_access
      extrude: usb_access_d-1
      shift: [0, 0, case_d+.5pcb_d+bottom_pcb_gap]     
  _battery_cover:
    - name: battery_area
      extrude: pcb_d
      shift: [0, 0, case_y-pcb_d]
  pcb:
    - _pcb      
  switch_plate:
    - _switch_plate      
    - _battery_cover
  _bottom:
    - name: outer_area
      extrude: pcb_d
  _outer_block:
    - name: outer_area
      extrude: case_y
  _inner_block:
    - what: outline
      name: bottom_outline
      shift: [0, 0, case_d]
      extrude: case_y-case_d
    - what: case
      name: _standoffs
      operation: subtract
  _wall:
    - _outer_block
    - -_inner_block
  case:
    - _wall
    - _bottom
    - _pcb_support
    - _standoffs
    - -_holes
    - -_usb_cutout
    - -_reset_cutout
    - -_power_cutout
  case_plate_preview: # Assembly compatibility
    - case
    - what: case
      name: switch_plate
  case_pcb_preview: # Assembly compatibility
    - case
    - what: case
      name: _pcb
  pcb_plate_preview: # Assembly compatibility
    - switch_plate
    - what: case
      name: _pcb          