meta:
  name: pekepad
  version: 0.0.1
  engine: 4.1.0
  author: pedroren
units:
  k: u
  p: 1
  px: 4
  py: 2
  kpx: k+px
  kpy: k+py
  mcuy: 43.18
  mcux: 18.542
  # Defaults to M2 Screws
  screw_size: 1.5
  standoff_size: 2.5
  # Case
  case_d: 2
  pcb_d: 1.6
  plate_pcb_gap: 5
  bottom_pcb_gap: 4
  case_y: case_d+bottom_pcb_gap+pcb_d+plate_pcb_gap+pcb_d
  # Bottom support
  #4x12x30mm  
  batt_x: 12
  batt_y: 30
  batt_d: 4
points:
  zones:
    matrix:
      anchor:
        shift: [100, -120]
      key:
        padding: p+u
        spread: p+u
        tags: [switch]
      columns:
        outer:
          key.column_net: P008
          key.mirror.column_net: P031
        middle:
          key.column_net: P017
          key.mirror.column_net: P029
        inner:
          key.column_net: P020
          key.mirror.column_net: P002
      rows:
        bottom:
          row_net: P100
          mirror.row_net: P113
        top:
          row_net: P022
          mirror.row_net: P115
    encoders:
      key:
        padding: p+u
        spread: p+u
        tags: [encoder]
      anchor:
        ref.aggregate.parts: [matrix_outer_top,  matrix_outer_bottom]
        shift: [-1.1k, 0]
      columns:
        enccol:
          key.pin_a: P104
          key.pin_c: P106
          key.mirror.pin_a: P111
          key.mirror.pin_c: P009
          key.column_net: P008
          key.mirror.column_net: P031
      rows:
        encrow:
          row_net: P024
          mirror.row_net: P024
    mount1:
      key.tags: [mount]
      anchor:
        ref.aggregate.parts: [matrix_outer_top,  matrix_outer_bottom, matrix_middle_top,  matrix_middle_bottom]
    mount:
      key.tags: [mount]
      anchor:
        ref.aggregate.parts: [matrix_inner_top, matrix_inner_bottom]
        shift: [.5k,0]
  rotate: 0
  mirror: &mirror
    ref: matrix_inner_top
    distance: 2.8k
outlines:
  raw:
    - what: rectangle
      where: [switch,encoder,mcu]
      size: [k, k]
  keys_socket:
    - what: rectangle
      where: [switch]
      size: [14, 14]
  keys:
    - what: rectangle
      where: [switch]
      size: [k-0.5, k-0.5]
    #- what: rectangle
    #  where: tag.encoder
    #  size: [k-0.5, k-0.5]
  keys_area:
    - what: rectangle
      where: [switch]
      size: [5+k, 5+k]
      bound: true
      corner: px
  controller_area:
    - what: polygon
      fillet: 2
      points:
        - ref: matrix_inner_top
          shift: [.25k, .5k+3]
        - ref: mirror_matrix_inner_top
          shift: [.25k, .5k+3]
        - ref: mirror_matrix_inner_bottom
          shift: [.25k, -.6k]
        - ref: matrix_inner_bottom
          shift: [.25k, -.6k]
  battery_area:
    - what: rectangle
      where:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top,matrix_inner_bottom, mirror_matrix_inner_bottom]
      size: [1.5batt_x, batt_y+4]
      corner: 2
  battery_wall:
    - what: outline
      name: battery_area
      expand: case_d
      joints: beveled
  encoder_area:
    - what: rectangle
      where: [encoder]
      size: [2+k, 2+k]
      corner: px
  encoder_socket:
    - what: circle
      where: [encoder]
      radius: 3.5
  usb_access:
    - what: rectangle
      where:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0, 0.5k+1]
      size: [2mcux, 8]
  baseboard:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.5k, 0.5k]
        - ref: matrix_middle_top
          shift: [0, 0.5k]
        - ref: matrix_inner_top
          shift: [0, 0.5k]
        - ref: mirror_matrix_inner_top
          shift: [0, 0.5k]
        - ref: mirror_matrix_middle_top
          shift: [0, 0.5k]
        - ref: mirror_matrix_outer_top
          shift: [-0.5k, 0.5k]
        - ref: mirror_encoders_enccol_encrow
          shift: [-0.5k, 0.5k]
        - ref: mirror_encoders_enccol_encrow
          shift: [-0.5k, -0.5k]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5k, -0.5k]
        - ref: mirror_matrix_inner_bottom
          shift: [0, -0.5k]
        - ref: matrix_inner_bottom
          shift: [0, -0.5k]
        - ref: matrix_outer_bottom
          shift: [-0.5k, -0.5k]
        - ref: encoders_enccol_encrow
          shift: [-0.5k, -0.5k]
        - ref: encoders_enccol_encrow
          shift: [-0.5k, 0.5k]
  mounting:
    - what: circle
      radius: screw_size
      where: [mount]
  standoff:
    - what: circle
      radius: standoff_size
      where: [mount]
  inner_area:
    - baseboard
    - controller_area
    - encoder_area
  board:
    - inner_area
    - -standoff
  plate:
    - what: outline
      name: inner_area
      expand: .5
    - -keys_socket
    - -encoder_socket
    - -mounting
  outer_area:
    - what: outline
      name: board
      expand: case_d
      joints: beveled
  usb_wall:
    - what: outline
      name: usb_access
    - what: outline
      name: outer_area
      operation: intersect
  preview:
    - plate
    - -raw
    - -mounting
pcbs:
  switch_plate:
    template: kicad8
    outlines:
      main:
        outline: plate
  pekepad:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      gnd_fillzone:
        what: ceoloide/utility_filled_zone
        where:
          ref.aggregate.parts: [matrix_outer_top]
      mx_hotswap:
        what: ceoloide/switch_mx
        where: [switch]
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: [switch]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: '${KIPRJMOD}/../../../kicad/D_SOD-123.step'
        adjust:
          shift: [0, -5]
          rotate: 180
      diode_enc:
        what: ceoloide/diode_tht_sod123
        where: [encoder]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: '${KIPRJMOD}/../../../kicad/D_SOD-123.step'
          diode_3dmodel_xyz_rotation: [0,0,0]
        adjust:
          shift: [0, 4]
          rotate: 180
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -.25k]
          rotate: -0
        params:
          reversible: false
          P21: P031
          P20: P029
          P19: P002
          P18: P115
          P15: P113
          P14: P111
          P16: P010
          P10: P009
          P1: P006
          P0: P008
          P2: P017
          P3: P020
          P4: P022
          P5: P024
          P6: P100
          P7: P011
          P8: P104
          P9: P106
      encoders:
        what: ceoloide/rotary_encoder_ec11_ec12
        where: [encoder]
        params:
          A: "{{pin_a}}"
          C: "{{pin_c}}"
          S1: "{{colrow}}"
          S2: "{{column_net}}"
          mirror.S1: "{{column_net}}"
          mirror.S2: "{{colrow}}"
          include_plate_hole_marking: true
          include_plated_mounting_holes: false
        adjust:
          rotate: 0
      reset_button:
        what: ceoloide/reset_switch_smd_side
        params:
          side: B 
          reset_switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/Panasonic_EVQPUJ_EVQPUA.step'
          reset_switch_3dmodel_xyz_rotation: [0,0,0]
        where:
          ref.aggregate.parts: [matrix_inner_top]
          shift: [.7k,.5k+1]
          rotate: 0
      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          side: B
          switch_3dmodel_filename: '${KIPRJMOD}/../../../kicad/SW_SPDT_PCM12.step'
          switch_3dmodel_xyz_rotation: [0,0,90]
        where:
          ref.aggregate.parts: [mirror_matrix_inner_top]
          shift: [-.7k,.5k+1]
          rotate: 90
      batt_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: B
          battery_connector_3dmodel_filename: '${KIPRJMOD}/../../../kicad/JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal.step'
          battery_connector_3dmodel_xyz_rotation: [0,0,180]
          battery_connector_3dmodel_xyz_offset: [1, 0, 0]
        where:
          ref.aggregate.parts: [mirror_matrix_inner_top]
          shift: [-0.7k, 3]
          rotate: 0
      mounting_holes:
          what: ceoloide/mounting_hole_npth
          where: [mount]
      oled:
        what: ceoloide/display_nice_view
        params:
          side: "F"
          MOSI: P011
          SCK: P010
          CS: P006
        where:
          ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom,matrix_inner_top,mirror_matrix_inner_top]
          shift: [0,2]
          rotate: 0
cases:
  switch_plate:
    - name: plate
      extrude: pcb_d
    #- name: mounting
    #  extrude: plate_pcb_gap
    #  operation: subtract
  _pcb:
    - name: board
      extrude: pcb_d
  _holes:
    - name: mounting
      extrude: case_y
  _standoffs:
    - name: standoff
      extrude: case_y-pcb_d
  _usb_access_cut:
    - name: usb_wall
      extrude: 7 #Switchplate will cover the gap
  _bottom:
    - name: outer_area
      extrude: 1
  _outer_block:
    - name: outer_area
      extrude: case_y
  _inner_block:
    - what: outline
      name: board
      shift: [0, 0, case_d]
      extrude: case_y-case_d
    - what: case
      name: switch_plate
      shift: [0, 0, case_y-pcb_d]
    - what: case
      name: _standoffs
      operation: subtract
  _wall:
    - _outer_block
    - -_inner_block
  case:
    - _wall
    - what: case
      name: _usb_access_cut
      operation: subtract
      shift: [0, 0, case_y-plate_pcb_gap-pcb_d] 
    - _bottom
    - _standoffs
    - -_holes
    - what: outline
      name: battery_wall
      extrude: bottom_pcb_gap
      shift: [0, 0, case_d]
    - what: outline
      name: battery_area
      extrude: bottom_pcb_gap
      shift: [0, 0, case_d]
      operation: subtract
  case_plate_preview: #Assembled case
    - case
    - what: case
      name: switch_plate
      shift: [0,0,case_y-pcb_d]
  case_pcb_preview: #Assembled case
    - case
    - what: case
      name: _pcb
      shift: [0,0,bottom_pcb_gap]
